<a href="https://colab.research.google.com/github/deep1185/ga-learner-dsmp-repo/blob/master/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# mount drive
from google.colab import drive
drive.mount('/drive',force_remount=True)

Mounted at /drive


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8350, 4173, 2286, 7438], [8350, 4173, 2286, 1747], [8350, 1785, 2286, 5440], [8603, 8189, 7598, 2484, 518], [8603, 8189, 7598, 2484, 9179], [3614, 8350, 4073, 2286, 3130], [1963, 6215, 291, 2484]]


Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8350 4173 2286 7438]
 [   0    0    0    0 8350 4173 2286 1747]
 [   0    0    0    0 8350 1785 2286 5440]
 [   0    0    0 8603 8189 7598 2484  518]
 [   0    0    0 8603 8189 7598 2484 9179]
 [   0    0    0 3614 8350 4073 2286 3130]
 [   0    0    0    0 1963 6215  291 2484]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813
    0.02209869  0.03384953  0.04889939 -0.04088215  0.00606898]
  [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813
    0.02209869  0.03384953  0.04889939 -0.04088215  0.00606898]
  [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813
    0.02209869  0.03384953  0.04889939 -0.04088215  0.00606898]
  [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813
    0.02209869  0.03384953  0.04889939 -0.04088215  0.00606898]
  [-0.02338955  0.02516613 -0.00159652  0.00797801  0.04621514
    0.03064236 -0.03216509 -0.0470438  -0.00927962  0.02360317]
  [-0.0036443   0.02519364  0.02362945  0.01325383 -0.02773346
    0.01963892 -0.01093345  0.02538024  0.00161784 -0.00069463]
  [ 0.0352521   0.02977486  0.04259912 -0.02102716 -0.02911915
    0.00322247 -0.03098007 -0.03023212 -0.01144455  0.02889185]
  [ 0.01048111  0.03472267  0.04492775 -0.00720111 -0.02662273
    0.00482322  0.01184615 -0.02878305  0.027952

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8350, 4173, 2286, 7438], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

[[ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813  0.02209869
   0.03384953  0.04889939 -0.04088215  0.00606898]
 [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813  0.02209869
   0.03384953  0.04889939 -0.04088215  0.00606898]
 [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813  0.02209869
   0.03384953  0.04889939 -0.04088215  0.00606898]
 [ 0.02821423  0.00980499  0.00627432 -0.03507819 -0.00977813  0.02209869
   0.03384953  0.04889939 -0.04088215  0.00606898]
 [-0.02338955  0.02516613 -0.00159652  0.00797801  0.04621514  0.03064236
  -0.03216509 -0.0470438  -0.00927962  0.02360317]
 [-0.0036443   0.02519364  0.02362945  0.01325383 -0.02773346  0.01963892
  -0.01093345  0.02538024  0.00161784 -0.00069463]
 [ 0.0352521   0.02977486  0.04259912 -0.02102716 -0.02911915  0.00322247
  -0.03098007 -0.03023212 -0.01144455  0.02889185]
 [ 0.01048111  0.03472267  0.04492775 -0.00720111 -0.02662273  0.00482322
   0.01184615 -0.02878305  0.0279525   0.03994804]]